#!/usr/bin/env bash
# Reads /etc/passwd and displays the username, user id, and home directory path

while IFS=: read -r username password userid groupid userinfo homedir shell || [ -n "$username" ]; do
    echo "${username}:${userid}:${homedir}"
done < /etc/passwd
